# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Coding and Development Blog"
subtitle: "by Paul Cunningham"
title_separator: "|"
email: paul@paulcunningham.me
description: >- # this means to ignore newlines until "baseurl:"
  A coding blog by Paul Cunningham - author, entreprenuer, and online trainer.
twitter_username: paulcunningham
github_username: cunninghamp
minimal_mistakes_skin: default
search: true
repository: cunninghamp/cunninghamp.github.io

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Australia/Brisbane

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Analytics
analytics:
  provider               : google-gtag # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          : G-QFTH3F68C0
    anonymize_ip         : # true, false (default)

author:
  name   : "Paul Cunningham"
  avatar : "/assets/images/bio-photo.png"
  bio    : "Retired."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://paulcunningham.dev"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/cunninghamp"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/cunninghamp"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/cunninghamp"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/cunninghamp"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      classes: wide
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      classes: wide

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
